# Generated by Django 4.1.3 on 2022-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_colorvariant_delete_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='writters',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=50),
        ),
    ]
