# Generated by Django 4.1.3 on 2022-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_cast_movie_directors_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
