# Generated by Django 4.1.3 on 2022-11-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_summary_alter_movie_movie_desription'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.CharField(default='', max_length=100),
        ),
    ]
