# Generated by Django 4.1.3 on 2022-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_actor_directors_stars_writters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writters',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
        migrations.DeleteModel(
            name='Writters',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='movies.actor'),
        ),
    ]
