# Generated by Django 4.1.3 on 2022-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_actors_remove_movie_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.ImageField(default='black.jpg', upload_to='movie'),
        ),
    ]
