# Generated by Django 4.1.3 on 2022-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_imdb_rating_alter_movie_meta_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
