# Generated by Django 4.1.3 on 2022-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_title_image_alter_movieimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieimage',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='gallery_images',
            field=models.ManyToManyField(to='movies.movieimage'),
        ),
    ]
