# Generated by Django 4.1.3 on 2022-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movieimage_movie_movie_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
