# Generated by Django 4.1.3 on 2022-11-23 00:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_name', models.CharField(max_length=200, null=True)),
                ('review_text', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.ManyToManyField(to='movies.reviews'),
        ),
    ]
