# Generated by Django 4.1.3 on 2022-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_movie_reviews_delete_reviews_movie_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
