# Generated by Django 4.1.3 on 2022-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movie_user_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user_reviews',
        ),
        migrations.AddField(
            model_name='movie',
            name='user_reviews_imdb',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_reviews_meta',
            field=models.JSONField(null=True),
        ),
    ]
