# Generated by Django 4.1.3 on 2022-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_actor_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
