# Generated by Django 4.1.3 on 2022-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fav_movie_profile_fav_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_movies',
            field=models.ManyToManyField(to='accounts.fav_movie'),
        ),
    ]
