# Generated by Django 4.1.3 on 2022-11-24 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_watchlist_profile_watch_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('movie_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_list',
            field=models.ManyToManyField(to='accounts.watched'),
        ),
    ]
